spring:
  datasource:
    url:
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      default_batch_fetch_size: 100
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
